version: '3'

services:
  back-end:
    build: 
      context: ./services/back-end
      dockerfile: Dockerfile
    command: gunicorn --bind 0.0.0.0:5000 manage:app
    expose:
      - 5000
    env_file:
      - ./.env.prod